name: Deploy to Fly.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                             #v4.2.2
      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be         #v1.5

      - name: Set secrets and deploy
        run: |
          flyctl secrets set \
            BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
            SPREADSHEET_ID="${{ secrets.SPREADSHEET_ID }}" \
            GOOGLE_CREDS_JSON="${{ secrets.GOOGLE_CREDS_JSON }}"

          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
