name: Deploy to Fly.io

## yes, I test on production!
on: [push]

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                             #v4.2.2
      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be         #v1.5

      - name: Set secrets and deploy
        run: |
          # Convert JSON in one-liner for fly.io 
          echo "${{ secrets.GOOGLE_CREDS_JSON }}" | base64 | tr -d '\n' > creds_b64.txt
          b64_creds=$(cat creds_b64.txt)
          
          # Set secrets and deploy
          flyctl secrets set \
            BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
            SPREADSHEET_ID="${{ secrets.SPREADSHEET_ID }}" \
            GOOGLE_CREDS_JSON="$b64_creds"

          # Keep only one machine running, important for the bot
          flyctl deploy --ha=false --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
