name: Deploy to Fly.io

## yes, I test on production!
on: [push]

jobs:
  deploy:
    name: Deploy bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Link to Railway project
        run: railway link --project YOUR_PROJECT_ID

      - name: Set secrets
        run: |
          railway secrets set BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          railway secrets set SPREADSHEET_ID="${{ secrets.SPREADSHEET_ID }}"
          railway secrets set GOOGLE_CREDS_JSON='${{ secrets.GOOGLE_CREDS_JSON }}'

      - name: Deploy app
        run: railway up